- db_scripts/mosip_idp/ddl/idp-client_detail.sql
- idp-service/.gitignore
- idp-service/pom.xml
- idp-service/src/main/java/io/mosip/idp/IdpServiceApplication.java
- idp-service/src/main/java/io/mosip/idp/advice/ExceptionHandlerAdvice.java
- idp-service/src/main/java/io/mosip/idp/controllers/ClientDetailController.java
- idp-service/src/main/java/io/mosip/idp/controllers/InternalApiController.java
- idp-service/src/main/java/io/mosip/idp/controllers/OpenIdConnectController.java
- idp-service/src/main/java/io/mosip/idp/domain/ClientDetail.java
- idp-service/src/main/java/io/mosip/idp/dto/ClientReqDto.java
- idp-service/src/main/java/io/mosip/idp/dto/ClientRespDto.java
- idp-service/src/main/java/io/mosip/idp/dto/ErrorDto.java
- idp-service/src/main/java/io/mosip/idp/dto/OauthReqDto.java
- idp-service/src/main/java/io/mosip/idp/dto/OauthRespDto.java
- idp-service/src/main/java/io/mosip/idp/dto/OtpReqDto.java
- idp-service/src/main/java/io/mosip/idp/dto/RequestWrapper.java
- idp-service/src/main/java/io/mosip/idp/dto/ResponseWrapper.java
- idp-service/src/main/java/io/mosip/idp/dto/TokenReqDto.java
- idp-service/src/main/java/io/mosip/idp/repositories/ClientDetailRepository.java
- idp-service/src/main/java/io/mosip/idp/services/ClientDetailService.java
- idp-service/src/main/java/io/mosip/idp/services/InternalApiService.java
- idp-service/src/main/resources/application.properties
- idp-service/src/test/java/io/mosip/idp/ClientDetailRepositoryTest.java
- idp-service/src/test/java/io/mosip/idp/IdpServiceApplicationTests.java
- idp-service/src/test/resources/application.properties
1. Inital setup of the project
2. Added IDP DDL script
3. Added Idp-service module
4. Added MPL2 license headers
> MOSIP-23535

- authentication-wrapper/src/main/java/io/mosip/idp/authwrapper/service/IdentityAuthenticationService.java
- authentication-wrapper/src/main/java/io/mosip/idp/authwrapper/service/MockAuthenticationService.java
- idp-core/src/main/java/io/mosip/idp/core/dto/AuthChallenge.java
- idp-core/src/main/java/io/mosip/idp/core/dto/AuthCodeRequest.java
- idp-core/src/main/java/io/mosip/idp/core/dto/ClientDetailCreateRequest.java
- idp-core/src/main/java/io/mosip/idp/core/dto/ClientDetailUpdateRequest.java
- idp-core/src/main/java/io/mosip/idp/core/dto/KycAuthRequest.java
- idp-core/src/main/java/io/mosip/idp/core/dto/OAuthDetailRequest.java
- idp-core/src/main/java/io/mosip/idp/core/dto/OtpRequest.java
- idp-core/src/main/java/io/mosip/idp/core/spi/AuthenticationWrapper.java
- idp-core/src/main/java/io/mosip/idp/core/util/ErrorConstants.java
- idp-core/src/main/java/io/mosip/idp/core/validator/OtpChannel.java
- idp-core/src/main/java/io/mosip/idp/core/validator/OtpChannelValidator.java
- idp-core/src/test/java/io/mosip/idp/core/ValidatorTest.java
- idp-service/src/main/resources/application-local.properties
- idp-service/src/main/resources/messages.properties
All these issues are included in a single commit as they all are about 
1. Duplicated error message issue.
2. No validation for OTPChannel, added "boolean isSupportedOtpChannel(String channel)" in authenticationWrapper.
> MOSIP-24691 MOSIP-24692 MOSIP-24695 MOSIP-24706 MOSIP-24688 MOSIP-24689 MOSIP-24629

- authentication-wrapper/src/main/java/io/mosip/idp/authwrapper/service/IdentityAuthenticationService.java
- authentication-wrapper/src/main/java/io/mosip/idp/authwrapper/service/MockKeyBindingWrapperService.java
- binding-service-impl/src/main/java/io/mosip/esignet/services/KeyBindingServiceImpl.java
- binding-service-impl/src/test/java/io/mosip/esignet/KeyBindingServiceTest.java
- esignet-integration-api/src/main/java/io/mosip/esignet/api/dto/KycExchangeDto.java
- esignet-integration-api/src/main/java/io/mosip/esignet/api/spi/KeyBinder.java
- esignet-integration-api/src/main/java/io/mosip/esignet/api/util/ErrorConstants.java
1. Added bindingAuthFactorType in the keybinding interface
2. Corrected config key name,
3. Added userInfoResponseType in kycexchangedto
> MOSIP-24923

- oidc-ui/src/constants/clientConstants.js
[MOSIP-25914](https://mosip.atlassian.net/browse/MOSIP-25914)
[MOSIP-25914]: https://mosip.atlassian.net/browse/MOSIP-25914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> link-status key name corrected

- pom.xml
> Revert "Temp fix for build issue"

- esignet-service/src/main/resources/application-local.properties
Added configuration for mock esignet integration impl
[MOSIP-26304](https://mosip.atlassian.net/browse/MOSIP-26304)
[MOSIP-26304]: https://mosip.atlassian.net/browse/MOSIP-26304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOSIP-26304 Updated application-local.properties

- oidc-ui/public/locales/ar.json
- oidc-ui/public/locales/default.json
- oidc-ui/public/locales/en.json
- oidc-ui/src/App.js
- oidc-ui/src/components/Authorize.js
- oidc-ui/src/components/NavHeader.js
- oidc-ui/src/components/OtpGet.js
[MOSIP-26353](https://mosip.atlassian.net/browse/MOSIP-26353) Recaptcha is not getting displayed in selected language.
[MOSIP-26353]: https://mosip.atlassian.net/browse/MOSIP-26353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> added multi-lang support for captcha MOSIP-26353

- oidc-ui/public/locales/default.json
- oidc-ui/src/App.js
- oidc-ui/src/components/Authorize.js
- oidc-ui/src/components/NavHeader.js
- oidc-ui/src/components/OtpGet.js
Added PR that got missed from the branch MOSIP-25524.
https://github.com/mosip/esignet/pull/148
> MOSIP-26353 added multi-lang support for captcha

- oidc-ui/src/components/Consent.js
Added master toggle button for scope & claims in consent page
> [ES-97] Option to select all the optional claims in e-Signet in the consent page

- oidc-ui/src/components/L1Biometrics.js
SBI Component: is moving to bottom on opening "Login with Biometric" option 2nd time
> [ES-95] SBI component comes at bottom

- .github/workflows/push_trigger.yml
- .github/workflows/release_chart.yml
- binding-service-impl/src/test/java/io/mosip/esignet/KeyBindingServiceTest.java
- consent-service-impl/src/main/java/io/mosip/esignet/repository/ConsentRepository.java
- consent-service-impl/src/main/java/io/mosip/esignet/services/ConsentServiceImpl.java
- consent-service-impl/src/test/java/io/mosip/esignet/ConsentDetailRepositoryTest.java
- consent-service-impl/src/test/java/io/mosip/esignet/ConsentServiceImplTest.java
- esignet-core/src/main/java/io/mosip/esignet/core/dto/OIDCTransaction.java
- esignet-core/src/main/java/io/mosip/esignet/core/spi/ConsentService.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/AuthorizationServiceImpl.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/ConsentHelperService.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/LinkedAuthorizationServiceImpl.java
- oidc-service-impl/src/test/java/io/mosip/esignet/services/ConsentHelperServiceTest.java
[ES-176]
[ES-177]
bug fixes for the above tickets
[ES-176]: https://mosip.atlassian.net/browse/ES-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ES-177]: https://mosip.atlassian.net/browse/ES-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ES-176] [ES-177]

- oidc-ui/package-lock.json
> Dependabot changes

- .github/workflows/push_trigger.yml
- consent-service-impl/src/main/java/io/mosip/esignet/entity/ConsentDetail.java
- db_scripts/mosip_esignet/ddl/esignet-consent.sql
- db_scripts/mosip_esignet/ddl/esignet-consent_history.sql
- oidc-service-impl/src/main/java/io/mosip/esignet/services/ConsentHelperService.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/LinkedAuthorizationServiceImpl.java
- oidc-service-impl/src/test/java/io/mosip/esignet/services/ConsentHelperServiceTest.java
* [BUGFIX] [ES-218]
Fixed inconsistency with consent action capture shared for authorize scopes in the workflow
* Added documentation
[ES-218]: https://mosip.atlassian.net/browse/ES-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ES-218 (#296)

- vci-service-impl/src/main/java/io/mosip/esignet/vci/services/VCIssuanceServiceImpl.java
- vci-service-impl/src/test/java/io/mosip/esignet/vci/services/VCIssuanceServiceTest.java
> Test case failure fix

- oidc-ui/src/components/Consent.js
- oidc-ui/src/pages/Consent.js
Fixed the issue of showing the consent page if url is modified by replacing login with consent in the login page.
Fixed the issue of e-Signet consent screen loads first without any claim details for few seconds then displays complete claim details on consent screen.
> [ES-244] [ES-304]

- esignet-core/src/main/java/io/mosip/esignet/core/dto/ProofKeyCodeExchange.java
> ES-386 ProofKeyCodeExchange is made serializable

- .github/workflows/tag.yaml
[MOSIP-25631]
[MOSIP-25631]: https://mosip.atlassian.net/browse/MOSIP-25631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-30055] updated tag.yaml

- oidc-ui/public/index.html
- oidc-ui/public/variables.css
- oidc-ui/src/App.css
- oidc-ui/src/components/Authorize.js
- oidc-ui/src/components/Background.js
- oidc-ui/src/pages/Login.js
- oidc-ui/src/services/authService.js
- Added theme configuration for signup banner
- Passing all query parameter from the authorize api to the signup ui page
> [ES-413] [ES-412] Theme configuration for signup banner & sending state parameter to signup page

- esignet-service/src/main/java/io/mosip/esignet/controllers/OAuthController.java
- esignet-service/src/main/java/io/mosip/esignet/controllers/SystemInfoController.java
- esignet-service/src/test/java/io/mosip/esignet/controllers/OAuthControllerTest.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/AuthorizationHelperService.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/LinkedAuthorizationServiceImpl.java
> MOSIP-26691

- oidc-ui/src/components/Form.js
- oidc-ui/src/components/OtpGet.js
- oidc-ui/src/components/Password.js
This reverts commit 1bd1687888fdf31dfceb5b0d5d901ae5bbc0effb.
It is decided to release this fix as a patch.
> Revert "[MODIFIED] resetting captchaToken with recaptcha wigdet"

- apitest/pom.xml
- apitest/testNgXmlFiles/esignetSuite.xml
Migrated Esignet API automation test suite to JAVA 21 upgrade.
> MOSIP-32363 JAVA 21 upgrade

- esignet-integration-api/src/main/java/io/mosip/esignet/api/validator/AuthChallengeFactorFormatValidator.java
- esignet-service/src/test/resources/application-test.properties
* added details of sunbird into readme file of esignet-service
* added KBA config in oidc-ui readme
* add logic to skip id-field check with challenge
* added id-field into test.properties
---------
> [INJIWEB-130]  add logic to skip id-field check with challenge (#682)

- .github/workflows/push-trigger.yml
- apitest/Dockerfile
- apitest/pom.xml
Rollback of esignet api test rig to Java 11.
> MOSIP-33946 - Rollback to Java11

- esignet-core/src/main/java/io/mosip/esignet/core/constants/Constants.java
- esignet-core/src/main/java/io/mosip/esignet/core/dto/OIDCTransaction.java
- esignet-core/src/main/java/io/mosip/esignet/core/spi/AuthorizationService.java
- esignet-core/src/main/java/io/mosip/esignet/core/spi/TokenService.java
- esignet-service/src/main/java/io/mosip/esignet/advice/HeaderValidationFilter.java
- esignet-service/src/main/java/io/mosip/esignet/controllers/AuthorizationController.java
- esignet-service/src/main/resources/application-local.properties
- oidc-service-impl/src/main/java/io/mosip/esignet/services/AuthorizationHelperService.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/AuthorizationServiceImpl.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/CacheUtilService.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/OAuthServiceImpl.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/TokenServiceImpl.java
- oidc-service-impl/src/test/java/io/mosip/esignet/services/AuthorizationServiceTest.java
1. Added validation of ID token in the authenticate endpoint.
2. created a separate cache to store the transaction when prepare-signup-redirect endpoint is invoked.
> ES-1053 ES-1064

- apitest/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
- apitest/src/main/java/io/mosip/testrig/apirig/testscripts/EsignetBioAuth.java
MOSIP-34397 - Updated MosipTestRunner for commenting encryptDecryptUtil.
> MOSIP-34397 - Updating MosipTestRunner

- esignet-service/pom.xml
pom update for esignet service module
> ES-esignet service pom update

- api-test/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
MOSIP-36454 - fixed build issue by adding suite setup in runner file
> MOSIP-36454 - fixed build issue by adding suite setup in runner file

- api-test/src/main/java/io/mosip/testrig/apirig/testscripts/SimplePostForAutoGenId.java
MOSIP-34827 - Fixed L2 flow api failure
> MOSIP-34827 - Fixed L2 flow api failure

- oidc-service-impl/src/main/java/io/mosip/esignet/services/AuthorizationHelperService.java
- oidc-service-impl/src/test/java/io/mosip/esignet/services/AuthorizationServiceTest.java
[ES-1992](https://mosip.atlassian.net/browse/ES-1992)
OAuth Details API is initiating the transaction despite a mismatch between the aud claim in the provided ID token and the clientId
[ES-1992]: https://mosip.atlassian.net/browse/ES-1992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ES-1992]  OAuth Details API is initiating the transaction despite a mismatch between the aud claim in the provided ID token and the clientId

- esignet-service/src/test/java/io/mosip/esignet/flows/AuthCodeFlowTest.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/TokenServiceImpl.java
- oidc-service-impl/src/test/java/io/mosip/esignet/services/TokenServiceTest.java
This reverts commit c5b775ae58063e8794ea22c3aa5be365e03b556f.
> Revert "[ES-2249] added jti validation for client_assertion (#1231)"

- api-test/src/main/java/io/mosip/testrig/apirig/esignet/utils/EsignetUtil.java
- api-test/src/main/resources/esignet/CreateOIDCClientV2/CreateOIDCClient.yml
- api-test/src/main/resources/esignet/UpdateOIDCClientV2/UpdateOIDCClient.yml
- Added "jti" field in the sign payload for the generate token Testcases.
- Clientnamemap field is added as an additional field, hence making the neg testcases into pos
> ES-2274 | ES-2273 - bug fixes

- api-test/pom.xml
- api-test/src/main/java/io/mosip/testrig/apirig/esignet/testscripts/SimplePostForAutoGenId.java
- api-test/src/main/java/io/mosip/testrig/apirig/esignet/utils/EsignetConstants.java
- api-test/src/main/resources/esignet/GetLinkStatus/GetLinkStatus.yml
- api-test/src/main/resources/esignet/LinkAuthorizationCode/LinkAuthorizationCode.yml
- changed commons released version in the pom file.
- Added condition to fix dSL failure.
- Changed valid error codes.
> ES-2282 | MOSIP-40948 - esignet failure fixes

- api-test/src/main/java/io/mosip/testrig/apirig/esignet/testrunner/MosipTestRunner.java
- api-test/src/main/java/io/mosip/testrig/apirig/esignet/utils/EsignetConfigManager.java
- api-test/src/main/java/io/mosip/testrig/apirig/esignet/utils/EsignetConstants.java
- changed latest pom version.
- adding runtime properties for mock ID plugin to enable pre configured otp
> MOSIP-33883 - Added logic to add runtime properties for mock ID plugin to enable pre configured otp

- oidc-ui/public/locales/ar.json
- oidc-ui/public/locales/en.json
- oidc-ui/public/locales/hi.json
- oidc-ui/public/locales/km.json
- oidc-ui/public/locales/kn.json
- oidc-ui/public/locales/ta.json
- oidc-ui/src/components/Authorize.js
- oidc-ui/src/components/ClaimDetails.js
- oidc-ui/src/components/Consent.js
- oidc-ui/src/components/Form.js
- oidc-ui/src/components/IdToken.js
- oidc-ui/src/constants/clientConstants.js
- oidc-ui/src/helpers/utils.js
- oidc-ui/src/pages/Consent.js
- oidc-ui/src/pages/Login.js
Attention and consent screen UI fixes. 
Fixed the issue where the UI was stuck when signup client was onboarded with multiple authFactors. 
Fixed the issue where KBI Login button was stuck with spinner when there is error response from authenticate api.
> [ES-2202] [ES-2204] [ES-2388] [ES-2389]

- api-test/README.md
- api-test/pom.xml
- deploy/esignet-apitestrig/README.md
MOSIP-42410 - Updated the readme file for config property and pom file for version 1.6.1
> MOSIP-42410 - Updated the readme file for config property and pom file for version 1.6.1

- esignet-core/src/main/java/io/mosip/esignet/core/constants/Constants.java
- esignet-core/src/main/java/io/mosip/esignet/core/constants/ErrorConstants.java
- esignet-core/src/main/java/io/mosip/esignet/core/dto/ClientDetail.java
- esignet-core/src/main/java/io/mosip/esignet/core/dto/OAuthDetailRequest.java
- esignet-core/src/main/java/io/mosip/esignet/core/dto/OIDCTransaction.java
- esignet-core/src/main/java/io/mosip/esignet/core/dto/PushedAuthorizationRequest.java
- esignet-core/src/main/java/io/mosip/esignet/core/spi/OAuthService.java
- esignet-service/src/main/java/io/mosip/esignet/controllers/OAuthController.java
- esignet-service/src/test/java/io/mosip/esignet/controllers/OAuthControllerTest.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/AuthorizationServiceImpl.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/OAuthServiceImpl.java
- oidc-service-impl/src/main/java/io/mosip/esignet/services/TokenServiceImpl.java
- oidc-service-impl/src/test/java/io/mosip/esignet/services/OAuthServiceTest.java
2414 - Add dpop_jkt in transaction
2415 - validatate jkt against dpop header in par and match jkt in transaction with dpopheader in token endpoint.
2416 - Add jkt in access token
> [ES-2414][ES-2415][ES-2416] handling dpopheader and dpop_jkt

- oidc-ui/src/components/Authorize.js
- oidc-ui/src/components/Form.js
- oidc-ui/src/components/IdToken.js
- oidc-ui/src/components/L1Biometrics.js
- oidc-ui/src/components/OtpVerify.js
- oidc-ui/src/components/Password.js
- oidc-ui/src/components/Pin.js
- oidc-ui/src/services/authService.js
> [ES-2499] ui_locales added for all auth_factor flow, buildredirectparam modified

- postman-collection/eSignet.postman_collection.json
- Added PKCE support in the Postman collection
> ES-2465 | Add PKCE support in the Postman collection
